services:
  api:
    build:
      context: .
      target: api
    networks:
      gadget-crawler:
    volumes:
      - .:/app
    working_dir: /app
    command: nest start api --watch
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo

  crawler:
    build:
      context: .
      target: crawler
    networks:
      gadget-crawler:
    volumes:
      - .:/app
    working_dir: /app
    command: nest start api --watch
    depends_on:
      - redis
      - mongo

  datahub:
    build:
      context: .
      target: datahub
    networks:
      gadget-crawler:
    volumes:
      - .:/app
    working_dir: /app
    command: nest start api --watch
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    networks:
      gadget-crawler:
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: superSecretPassword
    ports:
      - 6379:6379

  mongo:
    image: mongo
    networks:
      gadget-crawler:
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data:

networks:
  gadget-crawler: