apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub
spec:
  selector:
    matchLabels:
      app: datahub
  template:
    metadata:
      labels:
        app: datahub
    spec:
      containers:
        - name: datahub
          image: datahub
          ports:
            - containerPort: 3030
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: datahub
spec:
  selector:
    app: datahub
  ports:
    - name: http
      port: 3030
