apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
        - name: crawler
          image: crawler
          ports:
            - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: crawler
spec:
  selector:
    app: crawler
  ports:
    - name: http
      port: 3030
